name: music_player
description: A new Flutter music player application.

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0 
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.3.4
  assets_audio_player: ^3.0.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
